name: Firebase App Distribution Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Building release app
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '🚀') }}
    steps:
      - uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew bumpPatch assembleRelease

      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Get version number
        run: echo "##[set-output name=version;]$(cat app/build/outputs/apk/release/output-metadata.json | jq '.elements[0].versionName')"
        id: get_version

      - uses: EndBug/add-and-commit@v4
        with:
          add: app/version
          author_name: Vincent Guillebaud
          author_email: vincent.guillebaud31@gmail.com
          message: ${{ format('🔖 Version {0}', steps.get_version.outputs.version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ${{ env.SIGNED_RELEASE_FILE }}

  deploy:
    name: Deploy to App Distribution
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app-release-unsigned-signed.apk
